name: workflow on approve

on:
  workflow_dispatch:

jobs:
  deploy-stg:
    runs-on: ubuntu-latest
    if: github.event.workflow != null || (github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main')
    steps:
      - run: echo "ref is ${{ github.event.ref }}"
