name: workflow on approve

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow != null || (github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main')
    steps:
      - run: echo "executed"
