name: pr4

on:
  pull_request:
    types: [opened, synchronized]
    paths:
      - 'staging/**'

defaults:
  run:
    working-directory: ./staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - run: echo "${{ github.event.action }}"
 