name: workflow on pull request

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    steps:
      - id: script
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            let state = null;
            const { data: workflow } = await github.actions.getWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-stg.yml'
            });
            return workflow.id || '';
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit
          custom_payload: |
            {
              attachments: [{
                title: '${{ github.event.repository.name }}',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}`,
                color: '#ccc',
                callback_id: '${{ github.event.pull_request.head.ref }}',
                actions: [{
                  name: '${{ github.event.repository.name }}',
                  text: 'Deploy to staging',
                  type: 'button',
                  value: '${{ steps.script.outputs.result }}'
                }]
              }]
            }
        if: steps.script.outputs.result != ''
