name: Generate DB Schema Documents

on:
  schedule:
    - cron:  '20 9 * * 3'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  tbls:
    name: Generate Documents
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db 
          MYSQL_USER: tbls
          MYSQL_PASSWORD: tbls
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute migration
        run: |
          curl -sOL https://github.com/k0kubun/sqldef/releases/latest/download/mysqldef_linux_amd64.tar.gz
          tar xf mysqldef_linux_amd64.tar.gz
          MYSQL_PWD=tbls ./mysqldef --user=tbls --host=127.0.0.1 --file=db/schema/table.sql db
      - name: Execute tbls
        run: |
          curl -sL https://git.io/use-tbls > use-tbls.tmp
          . ./use-tbls.tmp
          rm ./use-tbls.tmp
          TBLS_DSN=mysql://tbls:tbls@127.0.0.1:3306/db tbls doc -f
      - name: Count uncommit files
        id: check_diff
        run: |
          file_count=$(git status --porcelain docs/schema | wc -l)
          echo "file_count=$file_count" >> $GITHUB_OUTPUT
      - name: Commit ER graph
        if: ${{ steps.check_diff.outputs.file_count != '0' }}
        run: |
          git add docs/schema
          git checkout -b fix/tbls
          git commit -m "docs: generate er graphs from actions"
          git push --set-upstream origin fix/tbls
          gh pr create -B main -H fix/tbls -t "Update table schema" -b ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
